export const a = 1;

/**
 * 
const colors = {
  red: "",
  orange: "",
  amber: "",
  yellow: "",
  Lime: "",
  green: "",
  emerald: "",
  teal: "",
  cyan: "",
  sky: "",
  blue: "",
  indigo: "",
  violet: "",
  purple: "",
  fuchsia: "",
  pink: "",
  rose: "",
  slate: "",
  gray: "",
  zinc: "",
  neutral: "",
  stone: "",
};

*/

export const primaryTextColors = {
  red: "text-red-600",
  orange: "text-orange-600",
  amber: "text-amber-600",
  yellow: "text-yellow-600",
  lime: "text-lime-600",
  green: "text-green-600",
  emerald: "text-emerald-600",
  teal: "text-teal-600",
  cyan: "text-cyan-600",
  sky: "text-sky-600",
  blue: "text-blue-600",
  indigo: "text-indigo-600",
  violet: "text-violet-600",
  purple: "text-purple-600",
  fuchsia: "text-fuchsia-600",
  pink: "text-pink-600",
  rose: "text-rose-600",
  slate: "text-slate-600",
  gray: "text-gray-600",
  zinc: "text-zinc-600",
  neutral: "text-neutral-600",
  stone: "text-stone-600",
};


export const primaryHoverTextColors = {
  red: "hover:text-red-600",
  orange: "hover:text-orange-600",
  amber: "hover:text-amber-600",
  yellow: "hover:text-yellow-600",
  lime: "hover:text-lime-600",
  green: "hover:text-green-600",
  emerald: "hover:text-emerald-600",
  teal: "hover:text-teal-600",
  cyan: "hover:text-cyan-600",
  sky: "hover:text-sky-600",
  blue: "hover:text-blue-600",
  indigo: "hover:text-indigo-600",
  violet: "hover:text-violet-600",
  purple: "hover:text-purple-600",
  fuchsia: "hover:text-fuchsia-600",
  pink: "hover:text-pink-600",
  rose: "hover:text-rose-600",
  slate: "hover:text-slate-600",
  gray: "hover:text-gray-600",
  zinc: "hover:text-zinc-600",
  neutral: "hover:text-neutral-600",
  stone: "hover:text-stone-600",
};

export const primaryBorderColors = {
  red: "border-red-600",
  orange: "border-orange-600",
  amber: "border-amber-600",
  yellow: "border-yellow-600",
  lime: "border-lime-600",
  green: "border-green-600",
  emerald: "border-emerald-600",
  teal: "border-teal-600",
  cyan: "border-cyan-600",
  sky: "border-sky-600",
  blue: "border-blue-600",
  indigo: "border-indigo-600",
  violet: "border-violet-600",
  purple: "border-purple-600",
  fuchsia: "border-fuchsia-600",
  pink: "border-pink-600",
  rose: "border-rose-600",
  slate: "border-slate-600",
  gray: "border-gray-600",
  zinc: "border-zinc-600",
  neutral: "border-neutral-600",
  stone: "border-stone-600",
};