query pageQuery {
  ...LayoutQueryFragment
  serieConnection {
    edges {
      node {
        id
        _values
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query serieQuery($relativePath: String!) {
  ...LayoutQueryFragment
  serie(relativePath: $relativePath) {
    ...SerieParts
  }
}

query seriesPublishedQuery {
  serieConnection(filter: { isPublished: { eq: true } }) {
    edges {
      node {
        title
        description
        summary
        meta {
          cover
          camera
          film
          tags
        }
        id
        publishedAt
        isPublished
        _sys {
          filename
        }
      }
    }
  }
}

query seriesFeaturedQuery {
  serieConnection(
    sort: "publishedAt"
    filter: { isPublished: { eq: true }, isFeatured: { eq: true } }
  ) {
    edges {
      node {
        title
        _body
        publishedAt
        isPublished
        isFeatured
        id
        _sys {
          filename
        }
      }
    }
  }
}

query seriesLatestsQuery {
  serieConnection(sort: "publishedAt", filter: { isPublished: { eq: true } }) {
    edges {
      node {
        title
        _body
        publishedAt
        isPublished
        isFeatured
        id
        _sys {
          filename
        }
      }
    }
  }
}
