query pageQuery {
  ...LayoutQueryFragment
  serieConnection {
    edges {
      node {
        id
        _values
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query serieQuery($relativePath: String!) {
  ...LayoutQueryFragment
  serie(relativePath: $relativePath) {
    ...SerieParts
  }
}

query seriesPublishedQuery {
  serieConnection(filter: { isPublished: { eq: true } }) {
    edges {
      node {
        title
        camera
        film
        location {
          city
          country
        }
        shot {
          start
          end
        }
        cover
        _body
        publishedAt
        isPublished
        id
        _sys {
          filename
        }
      }
    }
  }
}
