export const columnsOptionsCn = {
  default: {
    "1": "columns-1",
    "2": "columns-2",
    "3": "columns-3",
    "4": "columns-4",
    "5": "columns-5",
    "6": "columns-6",
    "7": "columns-7",
    "8": "columns-8",
  },
  sm: {
    "1": "sm:columns-1",
    "2": "sm:columns-2",
    "3": "sm:columns-3",
    "4": "sm:columns-4",
    "5": "sm:columns-5",
    "6": "sm:columns-6",
    "7": "sm:columns-7",
    "8": "sm:columns-8",
  },
  md: {
    "1": "md:columns-1",
    "2": "md:columns-2",
    "3": "md:columns-3",
    "4": "md:columns-4",
    "5": "md:columns-5",
    "6": "md:columns-6",
    "7": "md:columns-7",
    "8": "md:columns-8",
  },
  lg: {
    "1": "lg:columns-1",
    "2": "lg:columns-2",
    "3": "lg:columns-3",
    "4": "lg:columns-4",
    "5": "lg:columns-5",
    "6": "lg:columns-6",
    "7": "lg:columns-7",
    "8": "lg:columns-8",
  },
  xl: {
    "1": "xl:columns-1",
    "2": "xl:columns-2",
    "3": "xl:columns-3",
    "4": "xl:columns-4",
    "5": "xl:columns-5",
    "6": "xl:columns-6",
    "7": "xl:columns-7",
    "8": "xl:columns-8",
  },
};
